version: "3.9"
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 3000:3000
  api:
    build:    
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_HTTP_PORT: "https://+:5001"
      ASPNETCORE_URLS: "http://+:5000"
