# Build a custom base image with both .NET and Node.js
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs

# Build UI
FROM base as ui-build
WORKDIR /app/ui
COPY ui/package*.json ./
RUN npm install
COPY ui/ ./
RUN npm run build

# Build API
FROM base AS api-build
WORKDIR /app/api
COPY api/*.csproj ./
RUN dotnet restore
COPY api/ ./
RUN dotnet publish -c Release -o out

# Final Stage
FROM base
WORKDIR /app
COPY --from=api-build /app/api/out ./api
COPY --from=ui-build /app/ui/build ./ui

EXPOSE 5000
EXPOSE 5001
EXPOSE 3000

COPY start.sh .
RUN chmod +x start.sh
CMD ["./start.sh"]
