version: "3.9"
services:
  ui:
    image: khtestacr.azurecr.io/rna:rna-ui
    depends_on:
      - api
    ports:
      - 80:80 
  api:
    image: khtestacr.azurecr.io/rna:rna-api
    ports:
      - 5000:80
    environment:
      ASPNETCORE_URLS: "http://+:80"
