version: "3.9"
services:
  ui:
    image: khtestacr.azurecr.io/rna:rna-ui
    depends_on:
      - api
    ports:
      - 3000:3000
  api:
    image: khtestacr.azurecr.io/rna:rna-api
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_HTTP_PORT: "https://+:5001"
      ASPNETCORE_URLS: "http://+:5000"
