name: Push API to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: khtestacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t khtestacr.azurecr.io/rna:rna-api
        docker push khtestacr.azurecr.io/rna:rna-api
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'RandomNumberAppApi'
    #     slot-name: 'production'
    #     images: 'khtestacr.azurecr.io/rna:rna-api'
